### ISSUE TITLE
Empty `alt` attribute, and `store_labels` only works for reference links

### ISSUE THREAD

**Issue by elespike** [executablebooks/markdown-it-py#107]
**Describe the bug**

Image tokens always have an empty `alt` attribute, and the option `store_labels` doesn't work for inline links (only reference ones).

**To Reproduce**

```python
Python 3.8.3 (default, Jun  7 2020, 18:20:38) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from markdown_it import MarkdownIt                                                                     

In [2]: md = MarkdownIt()                                                                                      

In [3]: src = 'this is a ![picture](test.png "so nice") of a thing'                                            

In [4]: for t in md.parse(src): 
   ...:     if t.type == 'inline': 
   ...:         for c in t.children: 
   ...:             print(c) 
   ...:                                                                                                        
Token(type='text', tag='', nesting=0, attrs=None, map=None, level=0, children=None, content='this is a ', markup='', info='', meta={}, block=False, hidden=False)
Token(type='image', tag='img', nesting=0, attrs=[['src', 'test.png'], ['alt', ''], ['title', 'so nice']], map=None, level=0, children=[Token(type='text', tag='', nesting=0, attrs=None, map=None, level=0, children=None, content='picture', markup='', info='', meta={}, block=False, hidden=False)], content='', markup='', info='', meta={}, block=False, hidden=False)
Token(type='text', tag='', nesting=0, attrs=None, map=None, level=0, children=None, content=' of a thing', markup='', info='', meta={}, block=False, hidden=False)

In [5]: md.options['store_labels'] = True                                                                      

In [6]: for t in md.parse(src): 
   ...:     if t.type == 'inline': 
   ...:         for c in t.children: 
   ...:             print(c) 
   ...:                                                                                                        
Token(type='text', tag='', nesting=0, attrs=None, map=None, level=0, children=None, content='this is a ', markup='', info='', meta={}, block=False, hidden=False)
Token(type='image', tag='img', nesting=0, attrs=[['src', 'test.png'], ['alt', ''], ['title', 'so nice']], map=None, level=0, children=[Token(type='text', tag='', nesting=0, attrs=None, map=None, level=0, children=None, content='picture', markup='', info='', meta={}, block=False, hidden=False)], content='', markup='', info='', meta={}, block=False, hidden=False)
Token(type='text', tag='', nesting=0, attrs=None, map=None, level=0, children=None, content=' of a thing', markup='', info='', meta={}, block=False, hidden=False)
```

**Expected behavior**

Image tokens should have their `alt` attribute set here:
https://github.com/executablebooks/markdown-it-py/blob/16b85370f6ef538b50d4da15fa883e05be258c75/markdown_it/rules_inline/image.py#L140

And the `store_labels` option should add labels to inline links/images that aren't declared as references.

Bonus: does the label still need to be upper-cased in Python?
https://github.com/executablebooks/markdown-it-py/blob/16b85370f6ef538b50d4da15fa883e05be258c75/markdown_it/common/utils.py#L337

**Comment by chrisjsewell** [comment]
Heya, for the `alt` this is consistent with https://markdown-it.github.io/; it is actually added later in the renderer: https://github.com/executablebooks/markdown-it-py/blob/16b85370f6ef538b50d4da15fa883e05be258c75/markdown_it/renderer.py#L265-L277

so even though it is empty in the token you will still end up with: `<img src="test.png" alt="picture" title="so nice">`

The reason I think is that you can't determine the `alt` until all the image tokens children's have been parsed; so it has to be a post-processing step

Since this package aims to be a direct port of https://github.com/markdown-it/markdown-it, I would perhaps raise an issue there first if you still would like this changed.

**Comment by chrisjsewell** [comment]
> And the `store_labels` option should add labels to inline links/images that aren't declared as references.

I'm not quite sure what you mean by this. what would be the label for an inline link or image? Perhaps you could provide an example of the behaviour you would like cheers

**Comment by elespike** [comment]
Hi, @chrisjsewell 

Thanks for the responses =)

The `alt` can be known when parsing the image token because it happens to be the same as the label, whose positions are known:
https://github.com/executablebooks/markdown-it-py/blob/16b85370f6ef538b50d4da15fa883e05be258c75/markdown_it/rules_inline/image.py#L26-L27

But I'll take it up with `markdown-it` :+1: 

As for `store_labels` and inline links, the label is also what's within square brackets (which for images is also the `alt`), so in:
`this is a ![picture](test.png "so nice") of a thing`
I'd expect:
```
Token(type='image', tag='img', nesting=0, attrs=[['src', 'test.png'], ['alt', ''], ['title', 'so nice']], map=None, level=0, children=[...], content='', markup='', info='', meta={'label': 'PICTURE'}, block=False, hidden=False)
```

And the upper-casing is weird, but also an artifact of `markdown-it` =/ which probably won't change, they seem to have a JS-related reason for that.

Happy holidays! :tada:

**Comment by elespike** [comment]
:thinking: just noticed a discrepancy with `markdown-it`: they're effectively [adding the label into the `content` attribute](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22this%20is%20a%20!%5Bpicture%5D%20of%20a%20thing%5Cn%5Cn%5Bpicture%5D%3A%20test.png%20%5C%22so%20nice%5C%22%5Cn%5Cn%5Cnthis%20is%20a%20!%5Bpicture%5D%28test.png%20%5C%22so%20nice%5C%22%29%20of%20a%20thing%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22debug%22%7D%7D) of the image token, which `markdown-it-py` doesn't do.

And perhaps is the best solution.

**Comment by chrisjsewell** [comment]
Happy holidays! 🥳

Just for context, the `store_labels` option was added purely to achieve: https://github.com/executablebooks/mdformat/commit/ee503cdd06bb6b1a08a99582a7fa478bc0d08dfc,
i.e. for the Markdown renderer to be able to properly recover the link reference

Was there a particular use case you had in mind?

**Comment by elespike** [comment]
I'm writing some NLP functions that extract info directly from the tokens rather than render, then parse again. So I'm only looking to grab the label directly from the token.

Otherwise, I have to iterate again over its children. Just seemed weird to me that the link tokens wouldn't already include that info, so I did think it was a bug.

**Comment by chrisjsewell** [comment]
> just noticed a discrepancy with markdown-it

https://github.com/executablebooks/markdown-it-py/pull/113

**Comment by elespike** [comment]
Thank you! =)

That solves my issue, so since the `alt` and `store_labels` are working as intended, I'll close this up.

**Comment by chrisjsewell** [comment]
great thanks!
