### ISSUE TITLE
How to modify a document?

### ISSUE THREAD

**Issue by green-koopa** [executablebooks/markdown-it-py#112]
Is this an appropriate place to ask a question on basic use?

I have markdown files that I need to convert to html. This tool seems perfect. I also copied the markdown css from GitHub.

My complication is that I would like to modify the document. Between the parsing and the rendering seems intuitive to me, but I can't see that MarkdownIt is designed for that.

My current need is to keep some sections (from one heading_open to the next) and to discard others. I can also see merging documents or compiling a list of links from a document. I won't need anything too complex.

This is my thought:
```
import io
import markdown_it
from markdown_it import MarkdownIt

with open(r'abc.md', 'rt') as f_in:
    md_text = f_in.read()

md = MarkdownIt()
env = markdown_it.utils.AttrDict()

tokens = md.parse(md_text, env)

# modify the list of tokens here??

html = md.renderer.render(tokens, md.options, env)
```

Is this an appropriate approach for me to explore? Is markdown-it-py an appropriate tool for this use?

Python 3.9 on Windows 10

**Comment by chrisjsewell** [comment]
Heya, yeh that approach is perfectly legitimate, i.e. parsing to tokens, then separately rendering the tokens.
Equivalently, You could also consider adding a `core` plugin(s) that acts on the tokens after all other core rules.

See https://markdown-it-py.readthedocs.io/en/latest/architecture.html#data-flow and https://github.com/executablebooks/mdit-py-plugins/blob/5c0038fd4348cc37548b3ee7891a9f380517f959/mdit_py_plugins/footnote/index.py#L40, e.g.

```python
from markdown_it import MarkdownIt
from markdown_it.rules_block import StateBlock

def your_plugin(md: MarkdownIt):
    md.core.ruler.after("inline", "your_rule", rule_func)

def rule_func(state: StateBlock, *args, **kwargs):
    # do something with
	state.tokens
```

For merging documents, if you wanted to merge token lists then you would need to be wary if you were using links/link references and/or footnotes/footnote references (e.g. you would need to also merge `env`)

**Comment by chrisjsewell** [comment]
and of course feel free to suggest any improvements to the documentation 😄

**Comment by green-koopa** [comment]
Thank you! That is the laparoscopic approach I was hoping for. I was dumping all the insides out, which seemed unnecessary messy.

Along with all the more important things, I appreciate the type hinting in this project.

**Comment by chrisjsewell** [comment]
> Along with all the more important things, I appreciate the type hinting in this project.

ha thank @hukkinj1 for that

**Comment by green-koopa** [comment]
`thanks(target: User = hukkinj1):`
