### ISSUE TITLE
Circular Dependency with mdit-py-plugins on build

### ISSUE THREAD

**Issue by qandrew** [executablebooks/markdown-it-py#155]
**Describe the bug**
It seems like markdown-it-py requires mdit-py-plugins while mdit-py-plugins also requires markdown-it-py. This leads to a circular dependency when we build with Bazel, which fails. 

**To Reproduce**

Add to requirements.txt
```
markdown-it-py==0.6.2
mdit-py-plugins==0.2.6
```
Run `bazel build` on your package.

```
ERROR: /.cache/bazel/_bazel_devbox/efb427edc421a989d41cf3ac689374f5/external/pypi__36__markdown_it_py_0_6_2/BUILD:6:1: in py_library rule @pypi__36__markdown_it_py_0_6_2//:pkg: cycle in dependency graph:
    ....
    @pypi__36__jupytext_1_11_1//:pkg
.-> @pypi__36__markdown_it_py_0_6_2//:pkg
|   @pypi__36__mdit_py_plugins_0_2_6//:pkg
`-- @pypi__36__markdown_it_py_0_6_2//:pkg
This cycle occurred because of a configuration option
ERROR: Analysis of target '//src/python/***:image' failed; build aborted
```

**Expected behavior**
The package should be built without an issue.

When I run `pip install` locally pip seems to be able to resolve the circular dependency. 

**Environment**

- Python Version 3.6.9:
- Operating System: ubuntu18.04

**Additional context**

Thanks for your help!!

**Comment by chrisjsewell** [comment]
Yes I would maybe raise the issue with bazel. But anyhow mdit_py_plugins will already be removed from markdown-it-py in version 1.0

**Comment by qandrew** [comment]
Thanks! What is the timeline for releasing version 1.0?

**Comment by ashwin153** [comment]
Any update on a timeline?

**Comment by chrisjsewell** [comment]
Well this is essentially already closed in the 1.0.0b2 release that is already available on pypi

**Comment by ashwin153** [comment]
Awesome, thank you!

**Comment by chrisjsewell** [comment]
Cheers 😁
