### ISSUE TITLE
"Using the API demo" link is broken in GitHub README

### ISSUE THREAD

**Issue by huonw** [executablebooks/markdown-it-py#17]
The README on GitHub has a link "Using the api - for an executable notebook guide to the API", which points to https://github.com/executablebooks/markdown-it-py/tree/master/docs/Using_the_api.md . This link is currently dead.

It should potentially point to https://github.com/executablebooks/markdown-it-py/blob/master/docs/using.md ?

**Comment by choldgraf** [comment]
Yep thanks for spotting! I think that is the correct fix! Wanna make a quick PR and we can merge it in?
