### ISSUE TITLE
An md file, or notebook cell, ending in a blockquote with a blank line,  causes a crash

### ISSUE THREAD

**Issue by fperez** [executablebooks/markdown-it-py#185]
### Describe the bug

Consider a notebook that contains the following cell:

```
> test
>
```

or a markdown file with the above. The key point is that the cell/markdown content must _end with a blockquote that has a blank line at the end, still part of the block quote_. The python short traceback is (I'll attach the long one):

```python traceback
Exception occurred:
  File "/Users/fperez/local/conda/lib/python3.9/site-packages/markdown_it/rules_block/blockquote.py", line 158, in blockquote
    if state.srcCharCode[pos] == 0x20:  # /* space */
IndexError: tuple index out of range
```

### Reproduce the bug

Running a build with a notebook with the above (or an md file) should suffice.

### List your environment

```
> jupyter-book --version
Jupyter Book      : 0.11.3
External ToC      : 0.2.3
MyST-Parser       : 0.13.7
MyST-NB           : 0.12.3
Sphinx Book Theme : 0.1.10
Jupyter-Cache     : 0.4.3
NbClient          : 0.5.10
```

**Comment by fperez** [comment]
Full Sphinx error log:

[sphinx-err-06zb0e7h.log](https://github.com/executablebooks/markdown-it-py/files/7922070/sphinx-err-06zb0e7h.log)

**Comment by fperez** [comment]
@facusapienza21 - note this - Lab 1 for S159 was causing this crash and it took me a while to track down the issue.  Since it's a bug in markdown-it upstream, for now we can work around it by adding an extra blank line in cells that have block quotes, but I wanted you to be aware so you don't burn time on it...

**Comment by hukkin** [comment]
>  Since it's a bug in markdown-it upstream

To clarify, I don't think this is an issue in upstream Javascript markdown-it, but rather a porting issue in markdown-it-py.

I've fixed this in https://github.com/executablebooks/markdown-it-py/pull/186

**Comment by chrisjsewell** [comment]
Heya, yeh thanks, it is indeed a porting issue that I thought we had fully fixed already 😳.
Basically, for `array[outofbounds_index]` JS returns `null` (thus no crash) but Python raises an `IndexError`

**Comment by fperez** [comment]
Thanks folks for the super-quick response! And yes @hukkin - I meant markdown-it-py, sorry for being imprecise in the js/py distinction :) 

I greatly appreciate the quick fix, we'll roll it out into our working image once it's part of the next release.

**Comment by chrisjsewell** [comment]
cheers!
(FYI, in case you didn't notice, https://github.com/executablebooks/jupyter-book/issues/1181 was closed with jupyter-book v0.12)

**Comment by fperez** [comment]
Awesome - I hadn't noticed the 1181 fix, but that's much appreciated!

**Comment by chrisjsewell** [comment]
It's been hanging around at this "level", just had to float its way up to jupyter-book lol
