### ISSUE TITLE
MyPy Typechecking

### ISSUE THREAD

**Issue by 0az** [executablebooks/markdown-it-py#19]
As part of getting to learning how to hack on the package, I've started running MyPy for a "guided tour" of the API.

Do you mind if I send in one or more PRs to fix/silence some of the warnings?

**Comment by chrisjsewell** [comment]
Yeh go for it 👍

**Comment by 0az** [comment]
Something that I noticed when walking through the code:

There's a lot of untyped `dict`s and `AttrDicts` that probably can get replaced with dataclasses/attrs/namedtuple/etc.

Example:

```
def postProcess(state: StateInline):
    """Walk through delimiter list and replace text tokens with tags."""
    tokens_meta = state.tokens_meta
    maximum = len(state.tokens_meta)
    _postProcess(state, state.delimiters)

    curr = 0
    while curr < maximum:
        try:
            tokens_meta[curr]
        except IndexError:
            pass
        else:
            if tokens_meta[curr] and "delimiters" in tokens_meta[curr]:
                _postProcess(state, tokens_meta[curr]["delimiters"])
        curr += 1
```
`tokens_meta` can probably get swapped over to a TypedDict, or something like:
```
@dataclass
class TokenMetadata:
	delimiters: List[Delimiter]
```

The downside of TypedDict is that it's a 3.8+ feature, and some functionality requires `typing_extensions` until 3.9. One workaround could be using `__getitem__`/etc.

This is out of scope for what I intend, though.

**Comment by 0az** [comment]
@chrisjsewell Which test failures should I expect?

**Comment by chrisjsewell** [comment]
Which test failures should I expect?

None? 
I'm not sure if I understand what you, all the tests currently: https://github.com/executablebooks/markdown-it-py/actions/runs/105415163
Why would you expect some to fail?

FYI in-terma of mypy, you could just try add the pre-commit hook to the pre-commit config file, then fix the code accordingly: https://github.com/pre-commit/mirrors-mypy

**Comment by 0az** [comment]
Ah, sorry. I got a bug I introduced locally mixed up with some of the skipped tests.

Right now, there's around ~70 standing errors that I still need to fix, after grabbing the lowest hanging fruit, so I'll need to figure something out before adding a pre-commit hook.

**Comment by chrisjsewell** [comment]
Yeh no worries. The only thing to bear in mind is that we "shouldn't" (without very good reason) change the code in any way that deviates from the *source* [markdown-it](https://github.com/markdown-it/markdown-it) API.

Also I am definitely +1 for `TypedDict`, given that I am a big fan of TypeScript over JavaScript (essentially where this idea comes from), but yeh unfortunately it's a bit too early to be restricting the code to python 3.8+
