### ISSUE TITLE
Adds "tests" to top-level Python namespace

### ISSUE THREAD

**Issue by prescod** [executablebooks/markdown-it-py#20]
Thank you for markdown-it.py.

I've noticed that markdown-it-py adds a module called "tests" to site-packages. You can see that such a module is in the Wheel by unzipping it.

The tests direction should be excluded as described here:

https://setuptools.readthedocs.io/en/latest/setuptools.html#using-find-packages

**Comment by chrisjsewell** [comment]
Cheers, I didn’t notice that. Can probably just remove the `__init__.py` from the test folder

**Comment by choldgraf** [comment]
yeah - or explicitly remove it with a `MANIFEST` file I think
