### ISSUE TITLE
Gitpod launch failed due to missing requirement in python-attrs [cross-posting reported error]

### ISSUE THREAD

**Issue by CatChenal** [executablebooks/markdown-it-py#201]
### Problem:
I tried launching this repo via Gitpod: it failed on account of `attr` not being installed.

### Most likely cause:
The `attr` lib is not listed as a requirement for `python-attrs`.

### Reason for posting here:
This issue post is to:
 - let you know that I have posted [python-attrs issue 923](https://github.com/python-attrs/attrs/issues/923) to let them know.
 - let them know at least one consumer is waiting for them (after I obtain this issue number).

### Reproduce the bug

Launch the repo via Gitpod.

**Comment by CatChenal** [comment]
This is not an issue with `attrs`; amended issue title accordingly.  
Reported failed launch as [gitpod issue 8423](https://github.com/gitpod-io/gitpod/issues/8423).

**Comment by chrisjsewell** [comment]
Heya, the attrs dependency has now been removed (#212) so, once released, this should no longer be an issue
