### ISSUE TITLE
Dynamic AST

### ISSUE THREAD

**Issue by teucer** [executablebooks/markdown-it-py#21]
If a token has children and the parent should be recalculated from the children's attributes. E.g.

```python
from markdown_it import MarkdownIt
from markdown_it.extensions.front_matter import front_matter_plugin
from markdown_it.extensions.footnote import footnote_plugin

md = (
    MarkdownIt()
    .use(front_matter_plugin)
    .use(footnote_plugin)
    .disable('image')
    .enable('table')
)
text = "this result is `1+2`"
tokens = md.parse(text)
tokens[1].children[1].content = 3
html_text = md.render(text)
print(html_text)  # prints '<p>this result is <code>1+2</code></p>\n'
```
One could get instead
```html
<p>this result is <code>3</code></p>\n
```

The other attributes (e.g. type) could also be updated.

**Comment by chrisjsewell** [comment]
In `html_text = md.render(text)` you are re-parsing from the original text, so it doesn't matter how you have modified the tokens.
To directly render the tokens, I believe you need to run `md.renderer.render(tokens, md.options)`.
Let me know how you get on 😄

**Comment by teucer** [comment]
It works with `md.renderer.render(tokens, md.options, {})`.

It requires an `env` parameter, but it is not used anywhere in the code(?)

**Comment by chrisjsewell** [comment]
> but it is not used anywhere in the code(?)

yes it is; its used to persist data between states, such as footnote references to name one example: https://github.com/executablebooks/markdown-it-py/blob/ef323827f523946a0b689e95c205249c84cd0b1d/tests/test_footnote/test_footnote.py#L275-L276

**Comment by chrisjsewell** [comment]
You should actually parse the env from parsing to the renderer, as is done in the render method, i.e.

```python
env = {}
tokens = md.parse(text, env)
md.renderer.render(tokens, md.options, env)
```

**Comment by chrisjsewell** [comment]
I'll close this as I think it its solved, but feel free to answer any more questions
