### ISSUE TITLE
"Empty" directives on 1 line?

### ISSUE THREAD

**Issue by paugier** [executablebooks/markdown-it-py#223]
### Context

In MyST, it can make sense to have "1 line fenced code block". It would for example allow [sphinx-exercise](https://github.com/executablebooks/sphinx-exercise) users to write

````
```{exercise-end}```
````

instead of 

````
```{exercise-end}
```
````

This would save some lines and improve the global readability in documents where there are tens of such directives.

Now, these 2 inputs give very different results (https://github.com/executablebooks/MyST-Parser/issues/617#issuecomment-1247296222), which is kind of surprising for the users.

See https://github.com/executablebooks/MyST-Parser/issues/617

### Proposal

I'm wondering if there is a strong reason not to parse 
```
```{exercise-end}```
```
as a fenced code block?

**Comment by hukkin** [comment]
Markdown-it-py follows the CommonMark spec, which mandates that

~~~markdown
```{exercise-end}```
~~~
must be parsed as an [inline code space](https://spec.commonmark.org/0.30/#code-span). Parsing it as a fenced code block is a spec violation.

**Comment by paugier** [comment]
Thanks for your answer!
