### ISSUE TITLE
Fence with `foo` in language

### ISSUE THREAD

**Issue by paugier** [executablebooks/markdown-it-py#224]
### Context

I understood thanks to https://markdown-it.github.io/ that
````
```{admonition} This is my `admonition`
This is my note
```
````
is not parsed as a `fence`. However, it seems that it can be useful and "natural" for MyST users. 

### Proposal

I wonder if it could be possible to use `` ` `` in the `info` field of a `fence`?

**Comment by chrisjsewell** [comment]
FYI, you can do this using tildes:

```

~~~{admonition} This is my `admonition`
This is my note
~~~

```

**Comment by chrisjsewell** [comment]
I think the above answered your issue 😄
