### ISSUE TITLE
Please add a SECUIRTY.md

### ISSUE THREAD

**Issue by eslerm** [executablebooks/markdown-it-py#231]
### Context

A Security Policy is needed for researchers who want to report vulnerabilities.

### Proposal

[ossf](https://github.com/ossf/oss-vulnerability-guide/blob/main/templates/security_policies/github_security_policy.md) and [LXD](https://github.com/lxc/lxd/security/policy) have good examples

### Tasks and updates

 - [ ] add SECURITY.md

**Comment by eslerm** [comment]
There is a security section on https://markdown-it-py.readthedocs.io/en/latest/other.html

Could an email contact be added? Having that info on readthedocs and a SECURITY.md would be appreciated.

Disclosing security issues on the public bug tracker as readthedocs suggest may want to be reconsidered :D

**Comment by chrisjsewell** [comment]
Hey @eslerm 

See: cf8b2d8c561233d4c18c55e80b68c8d06850fda6 and 6491bc2491a07a8072e5d40f27eab6430585c42c

Does that look ok?

**Comment by eslerm** [comment]
That looks wonderful!

Thank you so much :pray:
