### ISSUE TITLE
Move plugins to seperate package?

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/markdown-it-py#30]
The core can almost be made v1.0.0 now since it won't change much outside porting new versions of markdown-it.
The plugins though can be more changeable, so should probably be moved to a different package, with a different release cadence

Its a bit of a pain though, for maintenance, if both are in different repositories.
But I've never housed to packages in the same repository before, so don't know if thats a good idea 🤷

**Comment by choldgraf** [comment]
something like `markdown-it-py-extra`?

Where do you envision the biggest pain points for maintenance? Are those things we could design automation / documentation / etc around? I have been impressed with the extent to which automating releases has made it relatively easy to have lots of smaller packages rather than one monorepo

**Comment by chrisjsewell** [comment]
> something like markdown-it-py-extra?

yeh or `markdown-it-py-plugins`

> Where do you envision the biggest pain points for maintenance? 

Let's just say its added hassle than I can be bothered with right now lol.
Nothing major really; you'd still want all the documentation centralised here, so (a minor thing) you couldn't use sphinx autodoc, maybe some other little things

**Comment by choldgraf** [comment]
quick thought: I think one benefit of those plugins being separate is that they could be used as examples for how others could extend `markdown-it-py` if they wished.

**Comment by chrisjsewell** [comment]
Oh yeh well they serve as that now, i.e. all folders in https://github.com/executablebooks/markdown-it-py/tree/master/markdown_it/extensions are self-contained plugins

**Comment by choldgraf** [comment]
yeah - I was just thinking if they were standalone packages then they could be almost like cookiecutters - just copy the package, swap out the bits for your custom extension, and publish on your own

**Comment by chrisjsewell** [comment]
Oh they're not **each** being separate packages though. That would be madness; they're only a few 100 lines of code max
