### ISSUE TITLE
New linkify rule does not linkify URLs entirely when they have a preceding `text` token

### ISSUE THREAD

**Issue by miteshashar** [executablebooks/markdown-it-py#300]
### Describe the bug

**context**

https://github.com/executablebooks/markdown-it-py/compare/v2.2.0...v3.0.0#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR21-R23

When I provide this input:
```
http://example.org/foo._bar_-_baz This works

This doesnt http://example.org/foo._bar_-_baz

While this `does` http://example.org/foo._bar_-_baz, this doesnt http://example.org/foo._bar_-_baz and this **does** http://example.org/foo._bar_-_baz

This applies to _series of URLs too_ http://example.org/foo._bar_-_baz http://example.org/foo._bar_-_baz, these dont http://example.org/foo._bar_-_baz http://example.org/foo._bar_-_baz and these **do** http://example.org/foo._bar_-_baz http://example.org/foo._bar_-_baz
```

**expectation**
I expect all URLs to get linkified correctly and entirely.

**bug**
But instead the ones indicated in the provided input do not get linkified.
<img width="1161" alt="image" src="https://github.com/executablebooks/markdown-it-py/assets/1172235/6bb42dc9-307f-4114-9f9c-47a7a6fdb980">

**problem**
This is a problem for people using URLs in their content, because they expect consistency in the output.

### Reproduce the bug

The provided input content suffices to indicate the use cases where the bug occurs.

### List your environment

markdown-it-py==3.0.0
mdit-py-plugins==0.4.0

Python version: 3.11.4
OS: MacOS

Markdown parser config:
- Preset: gfm-like
- html: False
- linkify: True
- typographer: True
- breaks: True
- plugins:
  - container_plugin for UI tabs: {'name': 'tab', 'marker': ':', 'render': [render_tab](https://github.com/hasgeek/funnel/tree/202b7fe/funnel/utils/markdown/tabs.py#L13)}
  - [abbr_plugin](https://github.com/hasgeek/funnel/tree/202b7fe/funnel/utils/markdown/mdit_plugins/abbr.py#L140)
  - [block_code_extend_plugin](https://github.com/hasgeek/funnel/blob/202b7fe53771c670c1f0db45da1f30c58eca2217/funnel/utils/markdown/mdit_plugins/block_code_ext.py#L36)
  - deflist_plugin
  - footnote_plugin
  - [footnote_extend_plugin](https://github.com/hasgeek/funnel/blob/202b7fe53771c670c1f0db45da1f30c58eca2217/funnel/utils/markdown/mdit_plugins/footnote_ext.py#L24C5-L24C27)
  - anchors_plugin: {'min_level': 1, 'max_level': 6, 'slug_func': lambda x: 'h:' + [make_name](https://github.com/hasgeek/coaster/blob/main/src/coaster/utils/misc.py#L287)(x), 'permalink': True, 'permalinkSymbol': '#', 'permalinkSpace': False}
  - [heading_anchors_fix_plugin](https://github.com/hasgeek/funnel/blob/202b7fe53771c670c1f0db45da1f30c58eca2217/funnel/utils/markdown/mdit_plugins/heading_anchors_fix.py#L43)
  - tasklists_plugin: {'enabled': True, 'label': True, 'label_after': False}
  - [ins_plugin](https://github.com/hasgeek/funnel/blob/202b7fe53771c670c1f0db45da1f30c58eca2217/funnel/utils/markdown/mdit_plugins/ins_tag.py#L159)
  - [sub_plugin](https://github.com/hasgeek/funnel/blob/202b7fe53771c670c1f0db45da1f30c58eca2217/funnel/utils/markdown/mdit_plugins/sub_tag.py#L99)
  - [sup_plugin](https://github.com/hasgeek/funnel/blob/202b7fe53771c670c1f0db45da1f30c58eca2217/funnel/utils/markdown/mdit_plugins/sub_tag.py#L99)
  - [mark_plugin](https://github.com/hasgeek/funnel/blob/202b7fe53771c670c1f0db45da1f30c58eca2217/funnel/utils/markdown/mdit_plugins/mark_tag.py#L159)
  - [embeds_plugin](https://github.com/hasgeek/funnel/tree/202b7fe/funnel/utils/markdown/mdit_plugins/embeds.py#L29): {'name': 'markmap'}
  - [embeds_plugin](https://github.com/hasgeek/funnel/tree/202b7fe/funnel/utils/markdown/mdit_plugins/embeds.py#L29): {'name': 'vega-lite'}
  - [embeds_plugin](https://github.com/hasgeek/funnel/tree/202b7fe/funnel/utils/markdown/mdit_plugins/embeds.py#L29): {'name': 'mermaid'}
- smartquotes: enabled

**Comment by tsutsu3** [comment]
There were no bugs in `linkify-it-py`. (It gave the same results as linkify-it.). There seems to be a problem with `markdown-it-py`.

A comparison of `linkify-it` and `linkify-it-py`, and a comparison of `markdown-it` and `markdown-it-py`.
result py:
```
# md render
<p><a href="http://example.org/foo._bar_-_baz">http://example.org/foo._bar_-_baz</a> This works</p>

<p>This doesnt <a href="http://example.org/foo">http://example.org/foo</a>.<em>bar</em>-_baz</p>

<p>While this <code>does</code> <a href="http://example.org/foo._bar_-_baz">http://example.org/foo._bar_-_baz</a>, this doesnt <a href="http://example.org/foo">http://example.org/foo</a>.<em>bar</em>-_baz and this <strong>does</strong> <a href="http://example.org/foo._bar_-_baz">http://example.org/foo._bar_-_baz</a></p>

<p>This applies to <em>series of URLs too</em> <a href="http://example.org/foo._bar_-_baz">http://example.org/foo._bar_-_baz</a> <a href="http://example.org/foo._bar_-_baz">http://example.org/foo._bar_-_baz</a>, these dont <a href="http://example.org/foo">http://example.org/foo</a>.<em>bar</em>-_baz <a href="http://example.org/foo">http://example.org/foo</a>.<em>bar</em>-_baz and these <strong>do</strong> <a href="http://example.org/foo._bar_-_baz">http://example.org/foo._bar_-_baz</a> <a href="http://example.org/foo._bar_-_baz">http://example.org/foo._bar_-_baz</a></p>

# linkify match
[linkify_it.main.Match({'schema': 'http:', 'index': 0, 'last_index': 33, 'raw': 'http://example.org/foo._bar_-_baz', 'text': 'http://example.org/foo._bar_-_baz', 'url': 'http://example.org/foo._bar_-_baz'})]
[linkify_it.main.Match({'schema': 'http:', 'index': 12, 'last_index': 45, 'raw': 'http://example.org/foo._bar_-_baz', 'text': 'http://example.org/foo._bar_-_baz', 'url': 'http://example.org/foo._bar_-_baz'})]
[linkify_it.main.Match({'schema': 'http:', 'index': 18, 'last_index': 51, 'raw': 'http://example.org/foo._bar_-_baz', 'text': 'http://example.org/foo._bar_-_baz', 'url': 'http://example.org/foo._bar_-_baz'}), linkify_it.main.Match({'schema': 'http:', 'index': 65, 'last_index': 98, 'raw': 'http://example.org/foo._bar_-_baz', 'text': 'http://example.org/foo._bar_-_baz', 'url': 'http://example.org/foo._bar_-_baz'}), linkify_it.main.Match({'schema': 'http:', 'index': 117, 'last_index': 150, 'raw': 'http://example.org/foo._bar_-_baz', 'text': 'http://example.org/foo._bar_-_baz', 'url': 'http://example.org/foo._bar_-_baz'})]
[linkify_it.main.Match({'schema': 'http:', 'index': 37, 'last_index': 70, 'raw': 'http://example.org/foo._bar_-_baz', 'text': 'http://example.org/foo._bar_-_baz', 'url': 'http://example.org/foo._bar_-_baz'}), linkify_it.main.Match({'schema': 'http:', 'index': 71, 'last_index': 104, 'raw': 'http://example.org/foo._bar_-_baz', 'text': 'http://example.org/foo._bar_-_baz', 'url': 'http://example.org/foo._bar_-_baz'}), linkify_it.main.Match({'schema': 'http:', 'index': 117, 'last_index': 150, 'raw': 'http://example.org/foo._bar_-_baz', 'text': 'http://example.org/foo._bar_-_baz', 'url': 'http://example.org/foo._bar_-_baz'}), linkify_it.main.Match({'schema': 'http:', 'index': 151, 'last_index': 184, 'raw': 'http://example.org/foo._bar_-_baz', 'text': 'http://example.org/foo._bar_-_baz', 'url': 'http://example.org/foo._bar_-_baz'}), linkify_it.main.Match({'schema': 'http:', 'index': 202, 'last_index': 235, 'raw': 'http://example.org/foo._bar_-_baz', 'text': 'http://example.org/foo._bar_-_baz', 'url': 'http://example.org/foo._bar_-_baz'}), linkify_it.main.Match({'schema': 'http:', 'index': 236, 'last_index': 269, 'raw': 'http://example.org/foo._bar_-_baz', 'text': 'http://example.org/foo._bar_-_baz', 'url': 'http://example.org/foo._bar_-_baz'})]

```

result js:
```
# md render
<p><a href="http://example.org/foo._bar_-_baz">http://example.org/foo._bar_-_baz</a> This works</p>

<p>This doesnt <a href="http://example.org/foo._bar_-_baz">http://example.org/foo._bar_-_baz</a></p>

<p>While this <code>does</code> <a href="http://example.org/foo._bar_-_baz">http://example.org/foo._bar_-_baz</a>, this doesnt <a href="http://example.org/foo._bar_-_baz">http://example.org/foo._bar_-_baz</a> and this <strong>does</strong> <a href="http://example.org/foo._bar_-_baz">http://example.org/foo._bar_-_baz</a></p>

<p>This applies to <em>series of URLs too</em> <a href="http://example.org/foo._bar_-_baz">http://example.org/foo._bar_-_baz</a> <a href="http://example.org/foo._bar_-_baz">http://example.org/foo._bar_-_baz</a>, these dont <a href="http://example.org/foo._bar_-_baz">http://example.org/foo._bar_-_baz</a> <a href="http://example.org/foo._bar_-_baz">http://example.org/foo._bar_-_baz</a> and these <strong>do</strong> <a href="http://example.org/foo._bar_-_baz">http://example.org/foo._bar_-_baz</a> <a href="http://example.org/foo._bar_-_baz">http://example.org/foo._bar_-_baz</a></p>

# linkify match
[
  Match {
    schema: 'http:',
    index: 0,
    lastIndex: 33,
    raw: 'http://example.org/foo._bar_-_baz',
    text: 'http://example.org/foo._bar_-_baz',
    url: 'http://example.org/foo._bar_-_baz'
  }
]
[
  Match {
    schema: 'http:',
    index: 12,
    lastIndex: 45,
    raw: 'http://example.org/foo._bar_-_baz',
    text: 'http://example.org/foo._bar_-_baz',
    url: 'http://example.org/foo._bar_-_baz'
  }
]
[
  Match {
    schema: 'http:',
    index: 18,
    lastIndex: 51,
    raw: 'http://example.org/foo._bar_-_baz',
    text: 'http://example.org/foo._bar_-_baz',
    url: 'http://example.org/foo._bar_-_baz'
  },
  Match {
    schema: 'http:',
    index: 65,
    lastIndex: 98,
    raw: 'http://example.org/foo._bar_-_baz',
    text: 'http://example.org/foo._bar_-_baz',
    url: 'http://example.org/foo._bar_-_baz'
  },
  Match {
    schema: 'http:',
    index: 117,
    lastIndex: 150,
    raw: 'http://example.org/foo._bar_-_baz',
    text: 'http://example.org/foo._bar_-_baz',
    url: 'http://example.org/foo._bar_-_baz'
  }
]
[
  Match {
    schema: 'http:',
    index: 37,
    lastIndex: 70,
    raw: 'http://example.org/foo._bar_-_baz',
    text: 'http://example.org/foo._bar_-_baz',
    url: 'http://example.org/foo._bar_-_baz'
  },
  Match {
    schema: 'http:',
    index: 71,
    lastIndex: 104,
    raw: 'http://example.org/foo._bar_-_baz',
    text: 'http://example.org/foo._bar_-_baz',
    url: 'http://example.org/foo._bar_-_baz'
  },
  Match {
    schema: 'http:',
    index: 117,
    lastIndex: 150,
    raw: 'http://example.org/foo._bar_-_baz',
    text: 'http://example.org/foo._bar_-_baz',
    url: 'http://example.org/foo._bar_-_baz'
  },
  Match {
    schema: 'http:',
    index: 151,
    lastIndex: 184,
    raw: 'http://example.org/foo._bar_-_baz',
    text: 'http://example.org/foo._bar_-_baz',
    url: 'http://example.org/foo._bar_-_baz'
  },
  Match {
    schema: 'http:',
    index: 202,
    lastIndex: 235,
    raw: 'http://example.org/foo._bar_-_baz',
    text: 'http://example.org/foo._bar_-_baz',
    url: 'http://example.org/foo._bar_-_baz'
  },
  Match {
    schema: 'http:',
    index: 236,
    lastIndex: 269,
    raw: 'http://example.org/foo._bar_-_baz',
    text: 'http://example.org/foo._bar_-_baz',
    url: 'http://example.org/foo._bar_-_baz'
  }
]
```

**Comment by tsutsu3** [comment]
ref [markdown-it demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22http%3A%2F%2Fexample.org%2Ffoo._bar_-_baz%20This%20works%5Cn%5CnThis%20doesnt%20http%3A%2F%2Fexample.org%2Ffoo._bar_-_baz%5Cn%5CnWhile%20this%20%60does%60%20http%3A%2F%2Fexample.org%2Ffoo._bar_-_baz%2C%20this%20doesnt%20http%3A%2F%2Fexample.org%2Ffoo._bar_-_baz%20and%20this%20%2A%2Adoes%2A%2A%20http%3A%2F%2Fexample.org%2Ffoo._bar_-_baz%5Cn%5CnThis%20applies%20to%20_series%20of%20URLs%20too_%20http%3A%2F%2Fexample.org%2Ffoo._bar_-_baz%20http%3A%2F%2Fexample.org%2Ffoo._bar_-_baz%2C%20these%20dont%20http%3A%2F%2Fexample.org%2Ffoo._bar_-_baz%20http%3A%2F%2Fexample.org%2Ffoo._bar_-_baz%20and%20these%20%2A%2Ado%2A%2A%20http%3A%2F%2Fexample.org%2Ffoo._bar_-_baz%20http%3A%2F%2Fexample.org%2Ffoo._bar_-_baz%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)
