### ISSUE TITLE
Skip the linkify test by default.

### ISSUE THREAD

**Issue by tsutsu3** [executablebooks/markdown-it-py#318]
### Context

I see issues that test fails due to lack of `linkify-it-py`. #312 #167 #191
With the default parser (commonmark), it works without `linkify-it-py`.
How about making the test also work without linkify-it-py by default?

### Proposal

`pytest tests`: Run tests (skip linkify tests)
`pytest tests --all`: Run all tests (with linkify tests)

**Comment by chrisjsewell** [comment]
No that's ok, these are all just issues from the same guy, that doesn't install the proper test dependencies
