### ISSUE TITLE
Please reduce the number of loggers and improve the naming schema

### ISSUE THREAD

**Issue by Zaczero** [executablebooks/markdown-it-py#330]
### Context

It is currently not possible to easily manage the loggers because of the sheer number of them.

https://github.com/search?q=repo%3Aexecutablebooks%2Fmarkdown-it-py+getLogger&type=code

Since this is a library intended to be used in other applications, I recommend reducing the number of loggers to 1 and giving it an easily rememberable name.

### Proposal

You can find some inspiration in the HTTPX library, which has just 2 loggers. Each one with a clear separation of responsibilities.

https://www.python-httpx.org/logging/

**Comment by chrisjsewell** [comment]
Heya, I feel you are misunderstanding how Python logging works; they are all children of the same root `markdown_it` logger, if you apply handlers/formatted to that then it will apply to all of them (unless you use `propagate=False`)

See https://docs.python.org/3/howto/logging.html

**Comment by Zaczero** [comment]
![image](https://github.com/executablebooks/markdown-it-py/assets/10835147/750391ad-8a8c-4e49-86eb-91b47f74df94)

Yes, my bad, you are right!
