### ISSUE TITLE
a url having an "&" to separate parameters is converted to "&amp;" and thereby broken

### ISSUE THREAD

**Issue by itcarroll** [executablebooks/markdown-it-py#337]
### Describe the bug

When I add markdown for a link with multiple query parameters, the HTML produced replaces `&` with `&amp;`. This results in query parameters being screwed up.

### Reproduce the bug

Do a `jb create book` and then add the following line to `book/intro.md`.
```
Here is a [link with borked parameters](https://www.youtube.com/watch?v=lZ2FHTkyaMU&t=5s).
```
Preview and try the (SFW) link ... the `t` parameter gets stripped because the url has `&amp;` rather than `&`.

### List your environment

```
$ jb --version
Jupyter Book      : 1.0.2
External ToC      : 1.0.1
MyST-Parser       : 2.0.0
MyST-NB           : 1.1.1
Sphinx Book Theme : 1.1.3
Jupyter-Cache     : 1.0.0
NbClient          : 0.10.0
```
```
markdown-it-py                3.0.0
mdit-py-plugins               0.4.1
```

Python 3.11.9 on Ubuntu jammy.

**Comment by chrisjsewell** [comment]
markdown-it-py correctly escapes `&` for the HTML, as per the HTML specification:

```
$ markdown-it       
markdown-it-py [version 3.0.0] (interactive)
Type Ctrl-D to complete input, or Ctrl-C to exit.
>>> [link with borked parameters](https://www.youtube.com/watch?v=lZ2FHTkyaMU&t=5s)
... ^D
<p><a href="https://www.youtube.com/watch?v=lZ2FHTkyaMU&amp;t=5s">link with borked parameters</a></p>
>>> 
```

anything else is an upstream bu

**Comment by itcarroll** [comment]
The link that works is `https://www.youtube.com/watch?v=lZ2FHTkyaMU&t=5s`. The link that `markdown-it-py` returns is `https://www.youtube.com/watch?v=lZ2FHTkyaMU&amp;t=5s`, where `&` has been replaced with `&amp;`. I agree that would be correct for representing text in HTML, but here in the `href` field it breaks the URL.

Try this URL in a browser: https://httpbin.org/anything/test?a=0&amp;b=1. The second parameter is interpreted as `amp;b` because `&` by itself is (correctly) interpreted as the query parameter separator.
