### ISSUE TITLE
Finalise port of non-standard rules to python

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/markdown-it-py#5]
These are just non-standard additional rules:

- [x] replacements (Simple typographic replacements)
- [x] smartquotes (Convert straight quotation marks to typographic ones)
- [ ] linkify (Replace link-like texts with link nodes.)

They are currently in the repo as their original `.js` files

**Comment by tsutsu3** [comment]
Ported linkify-it ([linkify-it-py](https://github.com/tsutsu3/linkify-it-py)).

Can I use [linkify-it-py](https://github.com/tsutsu3/linkify-it-py) as a dependency package for this project to implement linkify?

**Comment by chrisjsewell** [comment]
Heya yeh cheers, I think perhaps I'd but it as an extra
