### ISSUE TITLE
Issue with nested block-quote md syntax

### ISSUE THREAD

**Issue by mmcky** [executablebooks/markdown-it-py#50]
**Describe the bug**

The following markdown snippet causes `jupytext` conversion to fail with error (`IndexError: list index out of range`)

```
> `!conda install quantecon`
```

Is this an issue with nested literals?

It appears to be valid `md` using https://spec.commonmark.org/dingus/. 

**To Reproduce**

Add snippet to any `md` document

run

`jupytext doc.md --to ipynb`

**Expected behavior**

successful transfer to `ipynb`

**Environment**

- `markdown_it_py = 0.5.4`

**Comment by choldgraf** [comment]
does markdown-it-py parse that string properly as well? Does this error *only* pop up when used in conjunction with jupytext?

**Comment by chrisjsewell** [comment]
I'll copy the traceback you added on slack:

```python
  File "/Users/matthewmckay/anaconda3/envs/tomyst/lib/python3.8/site-packages/markdown_it/parser_block.py", line 58, in tokenize
    state.line = line = state.skipEmptyLines(line)
  File "/Users/matthewmckay/anaconda3/envs/tomyst/lib/python3.8/site-packages/markdown_it/rules_block/state_block.py", line 134, in skipEmptyLines
    if (self.bMarks[from_pos] + self.tShift[from_pos]) < self.eMarks[from_pos]:
IndexError: list index out of range
```

This is likely due to a porting issue in JS->Python whereby markdown-it works IMO a bit through luck rather than judgement in some places, in that JS does not raise an `IndexError` when retrieving an index larger than the length of the array but instead just returns `undefined`, and on top of that does not raise a `TypeError` when evaluating undefined against a number, e.g.

```javascript
>> a = [1, 2, 3]
>> console.log(a[4])
undefined
>> console.log(a[4] > 1)
false
```

so the fix will be something along the lines of:

```python
if from_pos < len(self.eMarks) and (self.bMarks[from_pos] + self.tShift[from_pos]) < self.eMarks[from_pos]:
```

**Comment by chrisjsewell** [comment]
@mmcky I've created a PR just with the snippet you gave, but this passes: #51

Can you work out the minimal preceding/following text from your full file, which can recreate the `IndexError`?

(tip: if you recreate this PR, you can just run `tox -- -k #50` to run the single test)

**Comment by mmcky** [comment]
thanks @chrisjsewell -- that syntax was the only change in a revision build of the migration for lecture-python-programming through https://github.com/QuantEcon/sphinxcontrib-tomyst/pull/61/files. 

I can't replicate this in a seperate `test` run so must have been an interaction with some other markup. I will close this PR for now and reopen if it crops up again.
