### ISSUE TITLE
Consider replacing AttrDict with built-in dict

### ISSUE THREAD

**Issue by hukkinj1** [executablebooks/markdown-it-py#66]
I can see the thinking for using an AttrDict for `options` and `env`: it provides a syntax that looks like JS object attribute access in "mother" markdown-it, and might make porting of JS extensions etc more straightforward.

I feel, however, that for the purpose the AttrDict is used for, i.e. a container of dynamically named data, a simple builtin dict might be the "Python native" equivalent.

The disadvantages of AttrDict that I can see:
- an added class for contributors to familiarize with
- adds confusion by providing two ways to do one thing, e.g. code like this looks buggy
  ```python
     if "key" in attr_dict:  # This hints at item access...
         attr_dict.key  # ...but then we do attribute access instead.
  ```
- When used as input type in public API, requires users to import the class and convert their dict.
- adds the AttrDict implementation code
- the dict interface can accidentally be broken by certain data, consider e.g.
  ```python
  >>> a = AttrDict({"values": 2})
  >>> a.values()
  Traceback (most recent call last):
    File "<input>", line 1, in <module>
  TypeError: 'int' object is not callable
  ```
- attribute access doesn't allow getting freely named data:
  ```python
  >>> a=AttrDict({"some-data": 4})
  >>> a.some-data
  Traceback (most recent call last):
    File "<input>", line 1, in <module>
  AttributeError: 'AttrDict' object has no attribute 'some'
  ```
- is a dreadful concept for type checkers :)

The advantages might be:
- ease of JS extension portability (although IMO, since a copy-paste won't suffice anyways, I feel like the "JS object -> Python dict" conversion could be seen as a necessary standard procedure for a porter)

**Comment by hukkinj1** [comment]
@chrisjsewell What do you think about this one? If you like the idea, then it would be a good idea to implement this before v1.0.0 I think.

**Comment by choldgraf** [comment]
I’ll defer to you two to decide, though I think the points you bring up here do make sense. It is always awkward using attribute for value retrieval when you can use keys that are not valid attribute names.
