### ISSUE TITLE
Plugin for task lists

### ISSUE THREAD

**Issue by wna-se** [executablebooks/markdown-it-py#75]
**Is your feature request related to a problem? Please describe.**

Ultimately I would like to add support for [GitHub style rendering of task lists](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/about-task-lists) using \[ \] and \[x\] in a downstream repository of executablebooks – e.g. jupyter-book – and I've tracked down this repository as a candidate for a pull request. 

**Describe the solution you'd like**

Porting a plugin for markdown-it such as [@hackmd/markdown-it-task-lists](https://www.npmjs.com/package/@hackmd/markdown-it-task-lists), source at  [revin/markdown-it-task-lists](https://github.com/revin/markdown-it-task-lists) to the extensions folder in this repository.

**Describe alternatives you've considered**

Creating a separate repository for the plugin and adding configuration options for external plugins to the downstream repositories MyST-Parser, MyST-NB and jupyter-book. This is a bigger task than I can do by myself.

**Additional context**

Se pull request.

**Comment by chrisjsewell** [comment]
thanks I will try to get round to looking to add this to myst-parser (and thus jupyter-book) soon (probably once #78 is merged)
