### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by hukkinj1** [executablebooks/markdown-it-py#79]
Hey @chrisjsewell !

I've made an [mdformat plugin](https://github.com/hukkinj1/mdformat-gfm) that makes mdformat compatible with Github Flavored Markdown. The plugin depends on `markdown-it-py` and `mdformat-tables` master branches as both have unreleased features that my plugin requires. Would be great if you'd find the time to make a release for these two projects, so I'd be able to change the git dependencies to PyPI dependencies and release my plugin.

This is in no way urgent though, just wanted you to know :smile: Thanks already!

**Comment by chrisjsewell** [comment]
Looks good 😄 yep I will put it on the TODO list 🥴

**Comment by chrisjsewell** [comment]
0.5.7 out 😄
