### ISSUE TITLE
Fix the more obscure backslash escape tests

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/markdown-it-py#8]
These are the final tests that need to be fixed; one that is directly applicable to CommonMark compliance, and the others are for additional compliance with markdown-it. They are all to do with how `\` escapes are treated for some of the more obscure cases in link titles / code fence languages, e.g. `[](<\&quot;> "\&amp;\&ouml;")`

- [x] https://github.com/ExecutableBookProject/markdown-it-py/blob/bc799d47e219fac146dd7f38f30641fb295a16fd/tests/test_cmark_spec/test_spec.py#L23
- [ ] https://github.com/ExecutableBookProject/markdown-it-py/blob/bc799d47e219fac146dd7f38f30641fb295a16fd/tests/test_port/test_fixtures.py#L28
- [ ] https://github.com/ExecutableBookProject/markdown-it-py/blob/bc799d47e219fac146dd7f38f30641fb295a16fd/tests/test_port/test_fixtures.py#L53
- [ ] https://github.com/executablebooks/markdown-it-py/pull/140/commits/f0c96ae5dbbbf0d27ed44e2f6ac237662a57001d (from https://github.com/markdown-it/markdown-it/commit/f156ed1bffec0e02b2353abf248c5b10c6101524)

**Comment by chrisjsewell** [comment]
Note the portability issue lies in the fact that markdown-it uses the external JS dependencies [mdurl](https://www.npmjs.com/package/mdurl) and [punycode](https://www.npmjs.com/package/punycode) for their functions, which are obviously not directly useable for python.

**Comment by chrisjsewell** [comment]
For the commonmark spec:

Backslash-escapes do not work inside autolinks:

```````````````````````````````` example
<http://example.com/\[\>
.
<p><a href="http://example.com/%5C%5B%5C">http://example.com/\[\</a></p>
````````````````````````````````

However, we get:

```
<p><a href="http://example.com/%5B%5C">http://example.com/\[\</a></p>
```

**Comment by chrisjsewell** [comment]
@hukkinj1 and @tsutsu3, given your recent work, perhaps you have an idea of how to solve these?
It doesn't seem that anyone has really come across issues with these, but it would be nice to solve if possible before a v1.0.0 release

**Comment by hukkinj1** [comment]
:+1: not picking this up right now, but I'll leave a comment here if I do later. Do these tests exist in JS markdown-it? Without the `skip`s? If yes, then the JS tests could be useful for debugging.

**Comment by chrisjsewell** [comment]
Yep the test fixtures are copied verbatim from the markdown-it repo: tests/test_port/fixtures, which are all formatted as inputs and expected outputs.

You "just" need to remove the skips and fix the code so they pass, **without** breaking any of the other tests.

I've tried before, but gave up after it felt like I was going round in circles lol: fixing one test but making another fail

**Comment by tsutsu3** [comment]
I tried it briefly before, but it didn't work. It was harder than I thought it would be. 😭

**Comment by chrisjsewell** [comment]
> It was harder than I thought it would be

same here!

**Comment by hukkinj1** [comment]
I was able to remove one of these skips here https://github.com/executablebooks/markdown-it-py/pull/97 admittedly without knowing what I was doing :smile: Hoping that I can trust our tests that I didnt break anything else...

**Comment by chrisjsewell** [comment]
thanks! yeh the tests are quite comprehensive, including the full commonmark specification.
But obviously if you can think of any other test cases, feel free to add them
